set serveroutput on;
BEGIN
	UPDATE EMP_CURSOR SET salary=salary*1.15
	WHERE emp_id='&emp_id';
	IF SQL%FOUND THEN
		DBMS_OUTPUT.PUT_LINE('MODIFIED');
	END IF;
	IF SQL%NOTFOUND THEN
		DBMS_OUTPUT.PUT_LINE('NOT MODIFIED');
	END IF;
END;
/