DECLARE
	CURSOR CSR IS SELECT EMP_ID, salary FROM EMP_CURSOR
		WHERE DEPT_NO='D05';
	eid EMP_CURSOR.EMP_ID%TYPE;
	sal EMP_CURSOR.salary%TYPE;

BEGIN
	OPEN CSR;
	IF CSR%ISOPEN THEN
		LOOP
			FETCH CSR INTO eid,sal;
			EXIT WHEN CSR%NOTFOUND;
			IF CSR%FOUND THEN
				UPDATE EMP_CURSOR SET salary=sal*1.1 WHERE emp_id=eid;
				INSERT INTO Emp_raise VALUES(eid, SYSDATE, sal*0.1);
			END IF;
		END LOOP;
		COMMIT;
	ELSE
		DBMS_OUTPUT.PUT_LINE('Unable to open the cursor');
	END IF;
	CLOSE CSR;
END;
/