# demonstrate the pre-defined String functions

s = input("Enter a string: ")

print("The string is: ", s)
print("The length of the string is: ", len(s))

print("The string in upper case is: ", s.upper())
print("The string in lower case is: ", s.lower())
print("The string in title case is: ", s.title())
print("The string in swap case is: ", s.swapcase())
print("The string in capitalize case is: ", s.capitalize())
print("The string in casefold case is: ", s.casefold())
print("The string in title case is: ", s.title())

print("Count of a in the string is: ", s.count('a'))
print("Check String is startswith a: ", s.startswith('a'))
print("Check String is endswith a: ", s.endswith('a'))
print("Find a in the string: ", s.find('a'))
print("Find last a in the string: ", s.rfind('a'))
print("Index of a in the string: ", s.index('a'))
print("Index of last a in the string: ", s.rindex('a'))
print("Replace a with b in the string: ", s.replace('a', 'b'))

print("Check String is alphanumeric: ", s.isalnum())
print("Check String is alphabetic: ", s.isalpha())
print("Check String is numeric: ", s.isnumeric())
print("Check String is upper: ", s.isupper())
print("Check String is lower: ", s.islower())
print("Check String is digit: ", s.isdigit())
print("Check String is space: ", s.isspace())
print("Check String is ascii: ", s.isascii())
print("Check String is decimal: ", s.isdecimal())
print("Check String is identifier: ", s.isidentifier())
print("Check String is printable: ", s.isprintable())

print("Center the string with *: ", s.center(20, '*'))
print("Left justify the string with *: ", s.ljust(20, '*'))
print("Right justify the string with *: ", s.rjust(20, '*'))
print("Zfill the string: ", s.zfill(20))
print("Partition the string with a: ", s.partition('a'))
print("Split the string with a: ", s.split('a'))
print("SplitLine the string: ", s.splitlines())
print("Strip the string: ", s.strip())
print("Strip the left string: ", s.lstrip())
print("Strip the right string: ", s.rstrip())
print("Make Translation of the string: ", s.maketrans('a', 'b'))
print("Translated String: ", s.translate(s.maketrans('a', 'b')))
print("Encode the string with utf-8: ", s.encode('utf-8'))
print("Expand the string: ", s.expandtabs(20))